---
abstract: 'two letter codes for state identification in the United States and vice versa.'
author:
  - 'Terrence Brannon'
build_requires:
  Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-US
requires:
  Data::Dumper: 0
  Data::Section::Simple: 0
version: 2.112140
